import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// Components
import Sidebar from "../../components/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Family Share</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center items-center max-w-4xl m-auto">
          <div className='px-6 py-64'>
            <Image 
              src='/icons/homeIcon.svg'
              alt='home Icon'
              width={100}
              height={100}
              className='m-auto mb-10'
            />
            <div className="text-center mb-16">
              <h1 className="text-5xl font-bold text-[#1B2C5D]">FamilyShare</h1>
              <h1 className="text-2xl font-semibold text-[#1B2C5D]">Share your next generation wallet with your loved ones.</h1>
            </div>
            <div className="flex justify-around">
              <Link href='onboarding'>
                <button className="py-2 w-32 bg-[#1B2C5D] font-semibold rounded-xl text-lg text-white hover:opacity-80 ease-in duration-200">
                  Parents
                </button>
              </Link>
              <button className="py-2 w-32 bg-[#1B2C5D] font-semibold rounded-xl text-lg text-white hover:opacity-80 ease-in duration-200">
                Kids
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
